export const PERMISSION_GROUPS: Record<string, { ar: string; en: string }> = {
  dashboard: { ar: "لوحة التحكم", en: "Dashboard" },
  contacts: { ar: "طلبات التواصل", en: "Contact Requests" },
  chat: { ar: "المحادثة المباشرة", en: "Live Chat" },
  services: { ar: "الخدمات", en: "Services" },
  projects: { ar: "الأعمال", en: "Projects" },
  articles: { ar: "المقالات", en: "Articles" },
  homepage: { ar: "الصفحة الرئيسية", en: "Homepage" },
  company: { ar: "الشركة", en: "Company" },
  social: { ar: "التواصل الاجتماعي", en: "Social Media" },
  media: { ar: "مكتبة الوسائط", en: "Media Library" },
  seo: { ar: "SEO", en: "SEO" },
  analytics: { ar: "التحليلات", en: "Analytics" },
  notifications: { ar: "الإشعارات", en: "Notifications" },
  users: { ar: "المستخدمون", en: "Users" },
  roles: { ar: "الأدوار والصلاحيات", en: "Roles & Permissions" },
  settings: { ar: "الإعدادات", en: "Settings" },
  integrations: { ar: "التكاملات", en: "Integrations" },
  audit: { ar: "سجل النشاطات", en: "Audit Log" },
};
