-- ============================================================================
-- Sitekoom — Content population (Static page SEO)
-- Uses the same static sentinel id used by the admin SeoFields component.
-- ============================================================================

insert into public.seo_metadata (entity_type, entity_id, locale, seo_title, meta_description, focus_keyword, keywords, canonical_url, og_title, og_description)
values
  ('services','00000000-0000-0000-0000-000000000000','ar',
   $c$خدماتنا الرقمية للشركات في الأردن | Sitekoom$c$,
   $c$استكشف خدمات Sitekoom الرقمية: تصميم المواقع، المتاجر الإلكترونية، البرمجة المخصصة، تطبيقات الموبايل وأنظمة ERP وPOS وCRM.$c$,
   $c$خدمات رقمية$c$,
   ARRAY[$c$خدمات رقمية$c$,$c$تصميم مواقع$c$,$c$متاجر إلكترونية$c$,$c$أنظمة ERP$c$],
   $c$/services$c$,
   $c$خدماتنا الرقمية للشركات في الأردن | Sitekoom$c$,
   $c$استكشف خدمات Sitekoom الرقمية للشركات في الأردن.$c$),
  ('projects','00000000-0000-0000-0000-000000000000','ar',
   $c$أعمالنا ومشاريعنا | Sitekoom$c$,
   $c$اطلع على أعمال Sitekoom ومشاريعها في تطوير المواقع والمتاجر والتطبيقات والأنظمة المخصصة للشركات.$c$,
   $c$أعمال Sitekoom$c$,
   ARRAY[$c$أعمال Sitekoom$c$,$c$مشاريع رقمية$c$,$c$بورتفوليو$c$],
   $c$/projects$c$,
   $c$أعمالنا ومشاريعنا | Sitekoom$c$,
   $c$اطلع على أعمال Sitekoom ومشاريعها الرقمية.$c$),
  ('blog','00000000-0000-0000-0000-000000000000','ar',
   $c$الأخبار والمقالات | Sitekoom$c$,
   $c$مقالات وأفكار حول التقنية، التحول الرقمي، تطوير المواقع والأنظمة ونمو الأعمال من مدونة Sitekoom.$c$,
   $c$مقالات تقنية$c$,
   ARRAY[$c$مقالات تقنية$c$,$c$التحول الرقمي$c$,$c$تطوير مواقع$c$],
   $c$/blog$c$,
   $c$الأخبار والمقالات | Sitekoom$c$,
   $c$مقالات وأفكار حول التقنية والتحول الرقمي من مدونة Sitekoom.$c$),
  ('request-project','00000000-0000-0000-0000-000000000000','ar',
   $c$ابدأ مشروعك مع سايتكم | Sitekoom$c$,
   $c$أخبرنا عن مشروعك واحتياجاتك وسنساعدك على تحديد الحل التقني الأنسب. اطلب عرض سعر الآن.$c$,
   $c$طلب مشروع$c$,
   ARRAY[$c$طلب مشروع$c$,$c$طلب عرض سعر$c$,$c$ابدأ مشروعك$c$],
   $c$/request-project$c$,
   $c$ابدأ مشروعك مع سايتكم | Sitekoom$c$,
   $c$أخبرنا عن مشروعك واحتياجاتك وسنساعدك على تحديد الحل الأنسب.$c$),

  ('services','00000000-0000-0000-0000-000000000000','en',
   $c$Digital Services for Businesses in Jordan | Sitekoom$c$,
   $c$Explore Sitekoom digital services: web design, e-commerce, custom software, mobile apps and ERP, POS and CRM systems.$c$,
   $c$digital services$c$,
   ARRAY[$c$digital services$c$,$c$web design$c$,$c$e-commerce$c$,$c$ERP systems$c$],
   $c$/services$c$,
   $c$Digital Services for Businesses in Jordan | Sitekoom$c$,
   $c$Explore Sitekoom digital services for businesses in Jordan.$c$),
  ('projects','00000000-0000-0000-0000-000000000000','en',
   $c$Our Work & Projects | Sitekoom$c$,
   $c$Explore Sitekoom projects in website, e-commerce, mobile application and custom system development.$c$,
   $c$Sitekoom projects$c$,
   ARRAY[$c$Sitekoom projects$c$,$c$digital projects$c$,$c$portfolio$c$],
   $c$/projects$c$,
   $c$Our Work & Projects | Sitekoom$c$,
   $c$Explore Sitekoom digital projects.$c$),
  ('blog','00000000-0000-0000-0000-000000000000','en',
   $c$News & Insights | Sitekoom$c$,
   $c$Articles and insights about technology, digital transformation, websites, software and business growth from the Sitekoom blog.$c$,
   $c$tech articles$c$,
   ARRAY[$c$tech articles$c$,$c$digital transformation$c$,$c$web development$c$],
   $c$/blog$c$,
   $c$News & Insights | Sitekoom$c$,
   $c$Articles and insights from the Sitekoom blog.$c$),
  ('request-project','00000000-0000-0000-0000-000000000000','en',
   $c$Start Your Project With Sitekoom | Sitekoom$c$,
   $c$Tell us about your project and requirements. Our team will help you identify the right digital solution. Request a quote now.$c$,
   $c$request a project$c$,
   ARRAY[$c$request a project$c$,$c$request a quote$c$,$c$start your project$c$],
   $c$/request-project$c$,
   $c$Start Your Project With Sitekoom | Sitekoom$c$,
   $c$Tell us about your project and we will help you identify the right solution.$c$)
on conflict (entity_type, entity_id, locale) do update set
  seo_title = excluded.seo_title,
  meta_description = excluded.meta_description,
  focus_keyword = excluded.focus_keyword,
  keywords = excluded.keywords,
  canonical_url = excluded.canonical_url,
  og_title = excluded.og_title,
  og_description = excluded.og_description;
