-- 16. Digital Marketing Strategy (new)
insert into public.services (slug, title_ar, title_en, icon, full_desc_ar, full_desc_en, category_id, status, sort, is_featured) values
('digital-marketing-strategy', 'الاستراتيجية والتسويق الرقمي', 'Digital Marketing Strategy', 'target',
 $desc$تساعد Sitekoom الشركات على بناء استراتيجيات تسويق رقمي واضحة بدل الاعتماد على النشر العشوائي أو الحملات التي لا ترتبط بأهداف محددة. تبدأ الاستراتيجية بدراسة طبيعة النشاط والمنتجات والخدمات والجمهور والمنافسين. نقوم بتحديد الأهداف التي تريد الشركة تحقيقها من خلال القنوات الرقمية. يمكن بناء تصور متكامل للمحتوى والإعلانات والتواصل مع العملاء. نحدد المنصات التي تتناسب مع طبيعة الجمهور والمنتج. يمكن إعداد استراتيجية خاصة بوسائل التواصل الاجتماعي والمحتوى والإعلانات. كما يمكن تحديد مراحل رحلة العميل من التعرف على العلامة التجارية إلى اتخاذ القرار. نعمل على اختيار مؤشرات الأداء التي يمكن استخدامها لقياس التقدم. يمكن مراجعة الحسابات والحملات الحالية وتحديد نقاط القوة والضعف. كما يمكن تحديد الفرص الجديدة التي يمكن استغلالها رقميًا. نضع خطة عملية يمكن تنفيذها بدل الاكتفاء بتوصيات نظرية عامة. يمكن تحديث الاستراتيجية بناءً على البيانات وسلوك الجمهور ونتائج الحملات. نربط بين المحتوى والإعلانات والموقع والصفحات المقصودة عند الحاجة. كما نساعد الشركة على ترتيب أولوياتها الرقمية وفق الموارد والأهداف. الهدف هو بناء استراتيجية واضحة تجعل التسويق الرقمي أكثر تنظيمًا وقابلية للقياس والتطوير.$desc$,
 $desc$Sitekoom helps businesses develop clear digital marketing strategies instead of relying on random posting or disconnected advertising activities. The process begins by studying the business, products, services, audience, market, and competitors. We identify the objectives the company wants to achieve through its digital channels. A connected approach can then be developed across content, advertising, communication, and customer acquisition. We identify the platforms that best match the target audience and business model. Social media, content, advertising, and digital communication strategies can be developed according to the company's priorities. Customer journey stages can also be considered, from brand awareness to engagement and conversion. We define meaningful performance indicators that can be used to measure progress. Existing accounts and campaigns can be reviewed to identify strengths, weaknesses, and opportunities. New digital opportunities can be identified according to market conditions and audience behavior. Our focus is on creating practical strategies that can actually be implemented rather than generic theoretical recommendations. Strategies can be refined as new performance data and customer insights become available. Content, advertising, websites, and landing pages can be connected into a more consistent digital journey. We also help businesses prioritize digital activities according to available resources and objectives. Our goal is to create a structured, measurable, and adaptable digital marketing strategy that supports sustainable business growth.$desc$,
 (select id from public.service_categories where slug='marketing'), 'published', 12, false)
on conflict (slug) do update set
  title_ar = excluded.title_ar,
  title_en = excluded.title_en,
  icon = excluded.icon,
  full_desc_ar = excluded.full_desc_ar,
  full_desc_en = excluded.full_desc_en,
  category_id = excluded.category_id;