-- 17. Community Management & Digital Engagement (new)
insert into public.services (slug, title_ar, title_en, icon, full_desc_ar, full_desc_en, category_id, status, sort, is_featured) values
('community-management', 'إدارة المجتمع والتفاعل الرقمي', 'Community Management & Digital Engagement', 'users',
 $desc$تقدم Sitekoom خدمات إدارة المجتمع والتفاعل الرقمي لمساعدة العلامات التجارية على بناء علاقة مستمرة مع جمهورها عبر منصات التواصل الاجتماعي. لا تقتصر الإدارة على نشر المحتوى، بل تشمل فهم التفاعل الذي يحدث بعد نشر المحتوى. يمكن متابعة التعليقات والرسائل والاستفسارات ضمن نطاق الخدمة المتفق عليه. نعمل على تقديم ردود تتناسب مع شخصية العلامة التجارية وأسلوبها في التواصل. يمكن تصنيف الاستفسارات وتحويل الحالات المهمة إلى الفريق المختص. كما يمكن إعداد أسلوب موحد للتعامل مع الأسئلة والشكاوى والملاحظات. نساعد على متابعة ردود فعل الجمهور تجاه المنتجات والخدمات والحملات. يمكن اكتشاف المواضيع والأسئلة التي تتكرر بين العملاء. هذه المعلومات يمكن أن تساعد الشركة على تحسين المحتوى والخدمات وتجربة العملاء. نعمل على المحافظة على سرعة استجابة مناسبة حسب طبيعة القناة وحجم التفاعل. يمكن دعم الحملات التسويقية من خلال زيادة التفاعل وتشجيع الجمهور على المشاركة. كما يمكن متابعة المؤشرات العامة للتفاعل وتحليل طبيعة الجمهور. يتم تطوير أسلوب التواصل مع مرور الوقت بناءً على التجارب والبيانات. يمكن دمج إدارة المجتمع مع Social Media Management وصناعة المحتوى والأتمتة. الهدف هو تحويل الحسابات الرقمية من مجرد قنوات للنشر إلى مساحات حقيقية للتواصل وبناء العلاقات مع العملاء.$desc$,
 $desc$Sitekoom provides community management services designed to help brands build stronger and more consistent relationships with their audiences across digital platforms. Community management goes beyond publishing content by focusing on the conversations and interactions that happen around the brand. Comments, messages, questions, and audience interactions can be monitored within the agreed scope of the service. Responses are aligned with the brand's communication style and personality. Important inquiries can be categorized and escalated to the appropriate team member. Clear communication guidelines can also be developed for questions, complaints, feedback, and recurring customer situations. Audience reactions to products, services, campaigns, and content can be monitored to identify useful insights. Recurring questions can reveal opportunities to improve content, services, and customer experiences. We focus on maintaining an appropriate response process based on the platform and volume of interactions. Community engagement can also support marketing campaigns by encouraging meaningful audience participation. Engagement patterns and audience responses can be reviewed to better understand the community. Communication practices can evolve over time based on customer feedback and performance data. Community management can be integrated with social media management, content creation, automation, and customer support. Our goal is to turn social media channels into active communication environments where brands can build trust, respond to customers, and maintain long-term relationships.$desc$,
 (select id from public.service_categories where slug='marketing'), 'published', 13, false)
on conflict (slug) do update set
  title_ar = excluded.title_ar,
  title_en = excluded.title_en,
  icon = excluded.icon,
  full_desc_ar = excluded.full_desc_ar,
  full_desc_en = excluded.full_desc_en,
  category_id = excluded.category_id;