-- 18. Social Media Content Design (new)
insert into public.services (slug, title_ar, title_en, icon, full_desc_ar, full_desc_en, category_id, status, sort, is_featured) values
('social-media-design', 'تصميم محتوى وسائل التواصل الاجتماعي', 'Social Media Content Design', 'image',
 $desc$تقدم Sitekoom خدمات تصميم محتوى وسائل التواصل الاجتماعي لمساعدة العلامات التجارية على الظهور بصورة بصرية متناسقة واحترافية عبر المنصات الرقمية. تبدأ عملية التصميم بفهم الهوية البصرية والألوان والخطوط والأسلوب الذي يمثل العلامة التجارية. يتم بناء أسلوب بصري يمكن استخدامه بشكل مستمر بدل تصميم منشورات منفصلة بلا هوية واضحة. يمكن تصميم المنشورات الثابتة والإعلانات والبطاقات المعلوماتية والمحتوى التعليمي والترويجي. كما يمكن تصميم Stories وReels Covers وغيرها من العناصر المناسبة للمنصات. نراعي المقاسات المختلفة ومتطلبات كل منصة عند تجهيز المحتوى. نركز على وضوح الرسالة وسهولة قراءة النصوص خصوصًا على شاشات الهواتف. يمكن استخدام الصور الاحترافية والرسومات والأيقونات والعناصر البصرية المختلفة. كما يمكن تطوير قوالب تساعد على تسريع إنتاج المحتوى المستقبلي. يمكن إنشاء تصاميم خاصة بالحملات والمناسبات والإطلاقات والعروض. نحرص على المحافظة على اتساق الألوان والخطوط والعناصر البصرية بين المنشورات. يمكن تطوير محتوى بصري مخصص للعلامات التجارية الجديدة أو للشركات التي تريد تحديث حضورها الرقمي. كما يمكن التنسيق بين التصميم وصناعة المحتوى والتصوير والإعلانات. الهدف هو بناء حضور بصري يجعل العلامة التجارية أكثر وضوحًا وتميزًا ويساعد الجمهور على التعرف عليها بسرعة.$desc$,
 $desc$Sitekoom provides social media design services that help brands maintain a professional, consistent, and recognizable visual presence across digital platforms. The design process begins by understanding the brand identity, colors, typography, visual language, and communication style. We create a visual system that can be maintained over time rather than producing unrelated posts without a consistent identity. Content can include static posts, advertisements, educational graphics, promotional materials, and informational designs. Stories, Reels covers, and other platform-specific assets can also be created. We consider the dimensions and requirements of each social media platform when preparing designs. Visual clarity and readable typography are especially important because much of social media content is viewed on smartphones. Professional photography, illustrations, icons, graphics, and other visual elements can be incorporated into the designs. Reusable templates can also be developed to make future content production more efficient. Campaign-specific designs can be created for promotions, launches, events, and seasonal activities. We maintain consistency across colors, typography, layouts, and other brand elements. Content can be developed for new brands or businesses looking to modernize their existing digital presence. Design can also be coordinated with photography, content creation, video production, and advertising campaigns. Our goal is to build a visual presence that makes the brand recognizable, professional, distinctive, and easier for its audience to remember.$desc$,
 (select id from public.service_categories where slug='marketing'), 'published', 14, false)
on conflict (slug) do update set
  title_ar = excluded.title_ar,
  title_en = excluded.title_en,
  icon = excluded.icon,
  full_desc_ar = excluded.full_desc_ar,
  full_desc_en = excluded.full_desc_en,
  category_id = excluded.category_id;