-- 19. Reels & Short-Form Content Production (new)
insert into public.services (slug, title_ar, title_en, icon, full_desc_ar, full_desc_en, category_id, status, sort, is_featured) values
('reels-short-content', 'إنتاج Reels والمحتوى القصير', 'Reels & Short-Form Content Production', 'video',
 $desc$تقدم Sitekoom خدمات إنتاج Reels والمحتوى القصير المصمم خصيصًا لطبيعة منصات التواصل الاجتماعي وسلوك المستخدم الحديث. يبدأ العمل بتحديد الفكرة والرسالة الأساسية التي يجب أن تصل خلال وقت قصير. يمكن تطوير سيناريوهات وأفكار متنوعة تتناسب مع العلامة التجارية والجمهور. يمكن تنفيذ التصوير من خلال فريق الإنتاج أو استخدام المواد المتوفرة لدى العميل حسب طبيعة المشروع. يتم تحرير الفيديو بطريقة تحافظ على سرعة الإيقاع وتمنع فقدان اهتمام المشاهد. يمكن إضافة النصوص والترجمة والعناوين والعناصر البصرية المناسبة. نراعي أهمية الثواني الأولى في جذب انتباه المستخدم. يمكن إنتاج سلسلة من الفيديوهات بدل الاعتماد على مقطع واحد. كما يمكن تحويل محتوى طويل إلى مجموعة من المقاطع القصيرة. يتم تجهيز الفيديوهات بالمقاسات المناسبة للمنصات المستهدفة. يمكن دمج الهوية البصرية والألوان والعناصر الخاصة بالعلامة التجارية. نعمل على تنويع الأفكار بين المحتوى التعليمي والترويجي والتفاعلي والتعريفي. يمكن استخدام Reels ضمن خطة Social Media أو الحملات الإعلانية. تتم مراجعة أداء المحتوى للاستفادة من النتائج في إنتاج الأفكار المستقبلية. الهدف هو بناء محتوى قصير مستمر يساعد العلامة التجارية على زيادة حضورها والتواصل مع الجمهور بطريقة سريعة وجذابة.$desc$,
 $desc$Sitekoom produces Reels and short-form content designed specifically for modern social media platforms and the way audiences consume short visual content. Each piece begins with a clear idea and a specific message that needs to be communicated within a limited amount of time. Concepts and short scripts can be developed according to the brand, audience, and campaign objectives. Content can be filmed by the production team or created using client-provided material depending on the project. Editing is designed to maintain pace and audience attention without unnecessary effects. Captions, titles, subtitles, and brand elements can be incorporated into the final content. Special attention is given to the opening seconds because they play an important role in capturing attention. Content can be produced as a consistent series rather than isolated videos. Long-form material can also be repurposed into multiple short-form pieces. Videos are prepared according to the required formats and dimensions of each platform. Brand identity can be integrated through colors, typography, graphics, and visual elements. We develop different content styles including educational, promotional, interactive, informative, and brand-focused videos. Reels can be incorporated into wider social media strategies and advertising campaigns. Performance insights can be used to improve future content concepts and formats. Our goal is to help brands build a consistent short-form content presence that communicates quickly, creatively, and effectively with their audiences.$desc$,
 (select id from public.service_categories where slug='marketing'), 'published', 15, false)
on conflict (slug) do update set
  title_ar = excluded.title_ar,
  title_en = excluded.title_en,
  icon = excluded.icon,
  full_desc_ar = excluded.full_desc_ar,
  full_desc_en = excluded.full_desc_en,
  category_id = excluded.category_id;