-- 20. Marketing Analytics & Reporting (new)
insert into public.services (slug, title_ar, title_en, icon, full_desc_ar, full_desc_en, category_id, status, sort, is_featured) values
('marketing-analytics', 'التحليلات والتقارير التسويقية', 'Marketing Analytics & Reporting', 'bar-chart',
 $desc$تقدم Sitekoom خدمات التحليلات والتقارير التسويقية لمساعدة الشركات على فهم أداء أنشطتها الرقمية واتخاذ قرارات مبنية على البيانات. تبدأ عملية التحليل بتحديد الأهداف والمؤشرات التي يجب قياسها وفق طبيعة المشروع. يمكن تحليل أداء حسابات التواصل الاجتماعي والمحتوى والحملات الإعلانية عند توفر البيانات اللازمة. نتابع مؤشرات مثل الوصول والتفاعل ونمو الجمهور والأداء الإعلاني حسب المنصة. يمكن مقارنة النتائج بين الفترات المختلفة لمعرفة الاتجاهات والتغيرات. كما يمكن تحديد أنواع المحتوى التي تحقق أداءً أفضل. تساعد التقارير الإدارة على فهم ما يحدث بدل الاكتفاء بمجموعة أرقام غير مفسرة. يمكن ربط البيانات من الأدوات المتاحة مثل Google Analytics وGoogle Ads ومنصات التواصل عند توفر التكامل. نعمل على تقديم المعلومات بطريقة منظمة وسهلة القراءة. يمكن تحديد نقاط القوة والجوانب التي تحتاج إلى تحسين. كما يمكن استخدام البيانات لاختيار الموضوعات والقنوات والحملات المستقبلية. تساعد التحليلات أيضًا على معرفة كيفية استخدام الميزانية الإعلانية بشكل أكثر كفاءة. يمكن إعداد تقارير دورية تساعد الفريق على متابعة التقدم. يتم تفسير النتائج ضمن سياق أهداف الشركة بدل اعتبار كل رقم نجاحًا أو فشلًا منفصلًا. الهدف هو تحويل البيانات الرقمية إلى رؤى عملية تساعد الشركات على تحسين التسويق واتخاذ قرارات أكثر وضوحًا.$desc$,
 $desc$Sitekoom provides marketing analytics and reporting services that help businesses understand the performance of their digital activities and make more informed decisions. The process begins by identifying the business objectives and the performance indicators that are relevant to those objectives. Social media, content, advertising, website, and campaign performance can be analyzed when the necessary data is available. Metrics such as reach, engagement, audience growth, advertising performance, and other platform-specific indicators can be reviewed. Results can be compared across different periods to identify trends, changes, and opportunities. High-performing content and campaigns can be identified to support future planning. Reports are designed to explain what the numbers mean rather than simply presenting large amounts of data. Available sources such as Google Analytics, Google Ads, and social media platforms can be connected when the appropriate integrations are available. Information is organized into clear reports that are easier for management teams to understand. Strengths and areas requiring improvement can be highlighted based on the available evidence. Data can support decisions about future content, advertising channels, campaigns, and budget allocation. Analytics can also help businesses understand how their marketing resources are being used. Periodic reports can provide a consistent view of progress and changes over time. Results are interpreted in the context of the company's actual objectives rather than treating individual metrics as isolated measures of success or failure. Our goal is to transform digital data into practical insights that help businesses improve their marketing and make clearer strategic decisions.$desc$,
 (select id from public.service_categories where slug='marketing'), 'published', 16, false)
on conflict (slug) do update set
  title_ar = excluded.title_ar,
  title_en = excluded.title_en,
  icon = excluded.icon,
  full_desc_ar = excluded.full_desc_ar,
  full_desc_en = excluded.full_desc_en,
  category_id = excluded.category_id;