-- ============================================================================
-- Sitekoom — Static page SEO content (provided content only, no invented data)
-- ============================================================================
insert into public.seo_metadata (entity_type, entity_id, locale, seo_title, meta_description, focus_keyword, keywords) values
('home', '00000000-0000-0000-0000-000000000000', 'ar',
 'سايتكم | حلول رقمية متكاملة لبناء المواقع والمتاجر والأنظمة والتسويق الرقمي',
 'سايتكم شركة متخصصة في تطوير المواقع الإلكترونية والمتاجر الإلكترونية والتطبيقات والأنظمة المخصصة، إلى جانب التسويق الرقمي وإدارة منصات التواصل الاجتماعي وصناعة المحتوى.',
 'شركة برمجة',
 ARRAY['شركة برمجة','تصميم مواقع','تطوير مواقع إلكترونية','برمجة مواقع','متاجر إلكترونية','تطبيقات موبايل','أنظمة ERP','أنظمة نقاط البيع','التسويق الرقمي','إدارة السوشال ميديا']),
('home', '00000000-0000-0000-0000-000000000000', 'en',
 'Sitekoom | Digital Solutions, Websites, E-commerce, Software & Digital Marketing',
 'Sitekoom provides digital solutions including website development, e-commerce stores, mobile applications, custom software, ERP and POS systems, digital marketing, social media management and content creation.',
 'web development company',
 ARRAY['web development company','website development','ecommerce development','mobile app development','custom software','ERP systems','POS systems','digital marketing','social media management']),
('about', '00000000-0000-0000-0000-000000000000', 'ar',
 'من نحن | سايتكم للحلول الرقمية والبرمجية والتسويق الرقمي',
 'تعرف على سايتكم، شركة متخصصة في بناء الحلول الرقمية وتطوير المواقع والمتاجر والتطبيقات والأنظمة المخصصة، مع خدمات التسويق الرقمي وإدارة منصات التواصل وصناعة المحتوى.',
 'من نحن', ARRAY['من نحن','سايتكم']),
('about', '00000000-0000-0000-0000-000000000000', 'en',
 'About Sitekoom | Digital Solutions & Technology Company',
 'Learn more about Sitekoom and our approach to building websites, e-commerce platforms, mobile applications, custom software, business systems and digital marketing solutions.',
 'about sitekoom', ARRAY['about sitekoom','digital solutions']),
('services', '00000000-0000-0000-0000-000000000000', 'ar',
 'خدمات سايتكم | البرمجة والتسويق الرقمي والحلول التقنية',
 'اكتشف خدمات سايتكم في تطوير المواقع والمتاجر والتطبيقات والأنظمة المخصصة، إضافة إلى التسويق الرقمي وإدارة السوشال ميديا والإعلانات والتصوير وصناعة المحتوى.',
 'خدمات سايتكم', ARRAY['خدمات سايتكم','البرمجة','التسويق الرقمي']),
('services', '00000000-0000-0000-0000-000000000000', 'en',
 'Sitekoom Services | Software Development & Digital Marketing',
 'Explore Sitekoom services including website development, e-commerce, mobile apps, custom software, ERP, POS, digital marketing, social media management, advertising, photography and content creation.',
 'sitekoom services', ARRAY['sitekoom services','software development','digital marketing']),
('projects', '00000000-0000-0000-0000-000000000000', 'ar',
 'أعمال سايتكم | مشاريع المواقع والمتاجر والتطبيقات والأنظمة والتسويق',
 'استعرض مجموعة من أعمال ومشاريع سايتكم في تطوير المواقع والمتاجر الإلكترونية والتطبيقات والأنظمة البرمجية والحلول الرقمية والتسويق وصناعة المحتوى.',
 'أعمال سايتكم', ARRAY['أعمال سايتكم','مشاريع']),
('projects', '00000000-0000-0000-0000-000000000000', 'en',
 'Sitekoom Portfolio | Websites, E-commerce, Apps & Digital Projects',
 'Explore Sitekoom portfolio of websites, e-commerce stores, mobile applications, custom software, business systems and digital marketing projects.',
 'sitekoom portfolio', ARRAY['sitekoom portfolio','digital projects']),
('contact', '00000000-0000-0000-0000-000000000000', 'ar',
 'اتصل بنا | سايتكم للحلول الرقمية',
 'تواصل مع فريق سايتكم للاستفسار عن خدمات البرمجة وتطوير المواقع والمتاجر والتطبيقات والأنظمة والتسويق الرقمي والحلول التقنية.',
 'اتصل بنا', ARRAY['اتصل بنا','سايتكم']),
('contact', '00000000-0000-0000-0000-000000000000', 'en',
 'Contact Sitekoom | Digital Solutions & Technology Services',
 'Contact Sitekoom to discuss website development, e-commerce, mobile apps, custom software, ERP, POS systems and digital marketing solutions.',
 'contact sitekoom', ARRAY['contact sitekoom']),
('request-project', '00000000-0000-0000-0000-000000000000', 'ar',
 'اطلب مشروعك | احصل على حل رقمي مخصص من سايتكم',
 'أرسل تفاصيل مشروعك إلى سايتكم واحصل على دراسة للحل الرقمي المناسب لمشروعك، سواء كان موقعًا إلكترونيًا أو متجرًا أو تطبيقًا أو نظامًا مخصصًا أو خدمة تسويق رقمي.',
 'اطلب مشروعك', ARRAY['اطلب مشروعك','حل رقمي']),
('request-project', '00000000-0000-0000-0000-000000000000', 'en',
 'Request Your Project | Get a Custom Digital Solution from Sitekoom',
 'Tell Sitekoom about your project and get a suitable digital solution for your business, from websites and e-commerce to mobile apps, custom systems and digital marketing.',
 'request your project', ARRAY['request your project','digital solution']),
('blog', '00000000-0000-0000-0000-000000000000', 'ar',
 'أخبار سايتكم | التقنية والبرمجة والتسويق والحلول الرقمية',
 'تابع أخبار ومقالات سايتكم حول تطوير المواقع والبرمجيات والتجارة الإلكترونية والتسويق الرقمي والتقنيات والحلول الرقمية.',
 'أخبار سايتكم', ARRAY['أخبار سايتكم','التقنية']),
('blog', '00000000-0000-0000-0000-000000000000', 'en',
 'Sitekoom News | Technology, Software & Digital Marketing',
 'Read Sitekoom articles and updates about web development, software, e-commerce, digital marketing, technology and digital business solutions.',
 'sitekoom news', ARRAY['sitekoom news','technology'])
on conflict (entity_type, entity_id, locale) do update set
  seo_title = excluded.seo_title,
  meta_description = excluded.meta_description,
  focus_keyword = excluded.focus_keyword,
  keywords = excluded.keywords;