-- ============================================================================
-- Sitekoom — 10 manual demo reviews (clearly marked source = 'manual')
-- These are DEMO content, NOT real Google reviews and not real people.
-- ============================================================================
insert into public.google_reviews (author_name, author_photo, rating, text_ar, text_en, language, review_date, review_url, sort, is_active, source) values
  ('أحمد الخطيب', null, 5, 'فريق Sitekoom صمم متجرنا الإلكتروني باحترافية عالية، والنتيجة فاقت توقعاتنا. سرعة التنفيذ كانت ممتازة والدعم مستمر حتى بعد الإطلاق.', 'The Sitekoom team built our online store with great professionalism, and the result exceeded our expectations. Execution was fast and support continued after launch.', 'ar', '2026-05-12', null, 1, true, 'manual'),
  ('سارة العلي', null, 5, 'تعاملنا معهم في تطوير تطبيق جوال، وكان التواصل واضحًا والتسليم في الموعد المحدد. جودة التصميم مميزة والتفاصيل دقيقة.', 'We worked with them on a mobile app, communication was clear and delivery was on time. The design quality is outstanding with precise details.', 'ar', '2026-06-03', null, 2, true, 'manual'),
  ('محمد النجار', null, 4, 'طوروا لنا نظام إدارة مخصص للشركة، سهّل علينا الكثير من العمليات اليومية. فريق محترف ويفهم احتياج العمل بدقة.', 'They developed a custom management system for our company that simplified many daily operations. A professional team that understands business needs precisely.', 'ar', '2026-04-21', null, 3, true, 'manual'),
  ('ليلى حسن', null, 5, 'أفضل تجربة مع شركة برمجيات. الموقع سريع ومتوافق مع الجوال بالكامل، والدعم الفني يستجيب بسرعة لأي استفسار.', 'Best experience with a software company. The website is fast and fully mobile-friendly, and technical support responds quickly to any question.', 'ar', '2026-07-08', null, 4, true, 'manual'),
  ('خالد العبدالله', null, 5, 'طلبت متجرًا إلكترونيًا متكاملًا وكانت النتيجة مذهلة. سهولة الإدارة والتصفح ممتازة، والمبيعات تحسنت بشكل ملحوظ بعد الإطلاق.', 'I ordered a complete e-commerce store and the result was amazing. Management and browsing are excellent, and sales improved noticeably after launch.', 'ar', '2026-05-29', null, 5, true, 'manual'),
  ('نور الهدى', null, 5, 'سرعة التنفيذ كانت مفاجأة سارة، وسلّموا المشروع قبل الموعد المتفق عليه. التصميم عصري ويوحي بالثقة للعملاء.', 'The speed of delivery was a pleasant surprise, and they delivered the project before the agreed date. The design is modern and inspires customer trust.', 'ar', '2026-06-17', null, 6, true, 'manual'),
  ('عمر الزعبي', null, 4, 'عمل احترافي في تطوير موقعنا، وتم مراعاة كل ملاحظاتنا أثناء التنفيذ. أنصح بالتعامل معهم لمن يبحث عن الجودة.', 'Professional work in developing our website, and all our feedback was taken into account during implementation. I recommend them for quality seekers.', 'ar', '2026-03-30', null, 7, true, 'manual'),
  ('ريم السالم', null, 5, 'فريق مبدع في التصميم والهوية البصرية. النتيجة النهائية كانت أفضل من المتوقع، والتواصل معهم كان سلسًا ومريحًا.', 'A creative team in design and branding. The final result was better than expected, and communication was smooth and comfortable.', 'ar', '2026-07-22', null, 8, true, 'manual'),
  ('فادي حداد', null, 5, 'طوّروا لنا منصة إلكترونية معقدة باحترافية عالية. الدعم بعد التسليم ممتاز وأي تعديل يتم بسرعة. شركة موثوقة.', 'They developed a complex web platform for us with high professionalism. Post-delivery support is excellent and any modification is done quickly. A reliable company.', 'ar', '2026-06-05', null, 9, true, 'manual'),
  ('هبة قاسم', null, 4, 'تجربة مميزة مع Sitekoom في تصميم موقع شركتنا. الواجهة أنيقة وسهلة الاستخدام، وفريق العمل متعاون ويستمع لكل التفاصيل.', 'A great experience with Sitekoom in designing our company website. The interface is elegant and easy to use, and the team is collaborative and attentive to details.', 'ar', '2026-05-15', null, 10, true, 'manual')
on conflict do nothing;
